### ISSUE TITLE
Repo missing `environments` folder

### ISSUE THREAD

**Issue by dartanian300** [TakaOtaku/Digimon-Card-App#456]
When attempting to clone the repo in order to contribute, the dev build fails due to a missing `/environments` folder.

<img width="1464" alt="Screen Shot 2023-01-03 at 10 43 27 AM" src="https://user-images.githubusercontent.com/3358537/210391559-6df20c5e-34e0-44e7-8341-662140c0365e.png">

**Comment by TakaOtaku** [comment]
Ohh yeah, sorry about that. As I didn't find other people interested in helping out with developing, I removed the folder and let git build it. 
Because I stored Firebase data and cardmarket API keys there.
Going to push them again in a few minutes, minus the cardmarket keys, so you can play around :D

If you got any questions you can add me on discord  TakaOtaku#8538.

**Comment by dartanian300** [comment]
Thanks! That resolved the build. I'm going to see if I can figure out why the modals aren't appearing on my phone. It's doing the same thing on my friend's phone so it's not isolated to just me.

**Comment by TakaOtaku** [comment]
I am going to my locals this Saturday, and I am gonna try it with their phones as well :)
