### ISSUE TITLE
unrelated! battle spirits saga deckbuilder?

### ISSUE THREAD

**Issue by justafamilyman** [TakaOtaku/Digimon-Card-App#468]
hi! i was wondering because for Digimon, I believe you have the most superior deckbuilder! will you have another deckbuilder for battle spirits saga when it releases in english? thanks!

**Comment by TakaOtaku** [comment]
Hey, that is nice of you to say, but I don't think I will have time for it.
This is also the reason why I didn't make one for the One Piece TCG.
But if I find someone who wants to make the site, I can help that person take the Digimon site as a blueprint and change it to any other TCG.

**Comment by justafamilyman** [comment]
Well hey, I'd be down to make the site! What's a guy gotta do?

**Comment by TakaOtaku** [comment]
Sure :) 
You would need programming experience though, then I can walk you trough each step.
The basic steps would be:
1.) Fork this Repo
2.) Change the Models/Interface to fit Battle Spirits instead of DIgimon
3.) Get the correct card images and card data, probably from the website or the wiki if there is one
4.) Start changing components
