### ISSUE TITLE
Suggest decks that match your collection

### ISSUE THREAD

**Issue by PauloBalbino** [TakaOtaku/Digimon-Card-App#487]
I would love to have the option to be able to filter decks I can make based on the collection I have.
This would enable to try out a bunch of new decks apart from the main ones with my leftover cards and check how the community uses the card I have laying around.

For example:

A user has 4 units of each of BT1 cards.
We would suggest all possible decks that he can make with that deck.
It would even be nicer if we would also suggest decks that contains most of the cards as well.

**Comment by PauloBalbino** [comment]
Working on this one right now. Will raise a branch soon.

**Comment by PauloBalbino** [comment]
I raised a PR for it, but now I ended up finding one thing that is felt more useful.
Which is sort the decks by amount of cards in deck.
I have developed that functionality locally but it is a bit heavy on the performance side. Will raise another PR when I have it up.

**Comment by TakaOtaku** [comment]
Looks good, I am in the process of reworking the deck page, so I will include your changes there :) 
I will load the decks of all users and disable the ability to share decks, as all created decks will be loaded. It will take a while longer to load because of 400 sites of decks instead of 30 so I am working on performance atm :)
