### ISSUE TITLE
Security key has no use?

### ISSUE THREAD

**Issue by WE-Kaito** [TakaOtaku/Digimon-Card-App#519]
![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/98795399/fac84629-a623-4222-9fc5-f35a8c8f93c0)

**Comment by TakaOtaku** [comment]
Some cards have a security effect some don't.
The card you screenshot yes should be Tanemon, this card doesn't have one.

**Comment by WE-Kaito** [comment]
Another example of memory boosts, where it is in the digivolutionEffect. Most have it in the inherited 😅
![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/98795399/54c463b9-1c69-4299-b858-997e4338d50f)

**Comment by TakaOtaku** [comment]
Ohh you're right there was an error since a few commits. The script wrote the security effect in the digivolve effect. 
Gonna be fixed with the next build tomorrow. Thank you 😁
![Screenshot_20231217-084648](https://github.com/TakaOtaku/Digimon-Card-App/assets/9803280/132e8428-8e9b-4fd1-ba09-87fab0b18f42)
